### PR TITLE
Fix a big in wait/notify processing in model checking

### LINKED ISSUE #76: IllegalMonitorStateException when using synchronized(object) { object.notifyAll(); }
I'm trying to test a simple lock structure using model checking. I have found that code of the form:

    synchronized (object) {
        object.notifyAll()
    }

results in an `IllegalMonitorStateException` as the current thread is apparently not the owner of the object's monitor. I would not have expected this exception as the object's monitor is clearly held at the time.

I have attached a piece of demonstration code. The exact output from Lincheck 2.12 is:

    Exception in thread "main" org.jetbrains.kotlinx.lincheck.LincheckAssertionError: 
    = The execution failed with an unexpected exception =
    Execution scenario (parallel part):
    | increment() |

    java.lang.IllegalMonitorStateException
        at java.lang.Object.notifyAll(Native Method)
        at DemoLincheckIssue$SimpleLock.unlock(DemoLincheckIssue.java:29)
        at DemoLincheckIssue.increment(DemoLincheckIssue.java:48)
        at org.jetbrains.kotlinx.lincheck.runner.TestThreadExecution48.run(Unknown Source)
        at org.jetbrains.kotlinx.lincheck.runner.FixedActiveThreadsExecutor$testThreadRunnable$1.run(FixedActiveThreadsExecutor.kt:163)
        at java.lang.Thread.run(Thread.java:748)

    = The following interleaving leads to the error =
    Parallel part trace:
    | increment()                                                                                              |
    |   lock.READ: SimpleLock@1 at DemoLincheckIssue.increment(DemoLincheckIssue.java:45)                      |
    |   lock() at DemoLincheckIssue.increment(DemoLincheckIssue.java:45)                                       |
    |   state.READ: 0 at DemoLincheckIssue.increment(DemoLincheckIssue.java:46)                                |
    |   state.WRITE(1) at DemoLincheckIssue.increment(DemoLincheckIssue.java:46)                               |
    |   state.READ: 1 at DemoLincheckIssue.increment(DemoLincheckIssue.java:47)                                |
    |   lock.READ: SimpleLock@1 at DemoLincheckIssue.increment(DemoLincheckIssue.java:48)                      |
    |   unlock(): threw IllegalMonitorStateException at DemoLincheckIssue.increment(DemoLincheckIssue.java:48) |
    |     MONITORENTER at DemoLincheckIssue$SimpleLock.unlock(DemoLincheckIssue.java:27)                       |
    |     owner.WRITE(null) at DemoLincheckIssue$SimpleLock.unlock(DemoLincheckIssue.java:28)                  |
    |     MONITOREXIT at DemoLincheckIssue$SimpleLock.unlock(DemoLincheckIssue.java:27)                        |
        at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.kt:51)
        at org.jetbrains.kotlinx.lincheck.LinChecker$Companion.check(LinChecker.kt:182)
        at org.jetbrains.kotlinx.lincheck.LinChecker$Companion.check$default(LinChecker.kt:181)
        at org.jetbrains.kotlinx.lincheck.LinChecker.check(LinChecker.kt)
        at DemoLincheckIssue.main(DemoLincheckIssue.java:53)

I seem to get the same output with Lincheck 2.11.

[DemoLincheckIssue.txt](https://github.com/Kotlin/kotlinx-lincheck/files/6098680/DemoLincheckIssue.txt)

### PR DESCRIPTION
**Pull request by alefedor**
Fixed several issues about `Object.wait()` and `Object.notify()` in the model checking mode.

### CODE REVIEW

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt [hunk 1]
```diff
@@ -864,7 +869,7 @@ private class MonitorTracker(nThreads: Int) {
     fun releaseMonitor(monitor: Any) {
         // Decrement the reentrancy depth and remove the acquisition info
         // if the monitor becomes free to acquire by another thread.
-        val ai = acquiredMonitors[monitor]!!
+        val ai = acquiredMonitors[monitor] ?: return
```
Comment (ndkoval) [inline src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt:872]: How can you invoke `release` without `acquire`?

**Review by ndkoval — APPROVED** [review]

File: src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt (hunk 1 above)
Comment (alefedor) [reply src/jvm/main/org/jetbrains/kotlinx/lincheck/strategy/managed/ManagedStrategy.kt]: I got an execution exception overrided by `NullPointerException` here, but this situation should not happen, so I reverted the change
